### ISSUE TITLE
feature: allow a custom location

### ISSUE THREAD

**Issue by mirsella** [edouardpoitras/bevy_text_popup#7]
hello !

Maybe by passing a Vec2 ?

thanks

**Comment by mirsella** [comment]
hm i think users can use the [TextPopupRootNode](https://docs.rs/bevy_text_popup/latest/bevy_text_popup/struct.TextPopupRootNode.html#) marker to set custom property

**Comment by edouardpoitras** [comment]
That's true. Although maybe it should be more of a 1st class option. I'll look into it.

**Comment by mirsella** [comment]
im starting to try to use this in my game, and the main problem is that we have to use two systems, one to send the event, and one after that that needs to find the correct root node, but there's no marker so no way of identifying which popup is which

**Comment by edouardpoitras** [comment]
I'm re-opening this because I want it to be an option moving forward. I will create another issue to allow the ability to add tag components to popups.

**Comment by mirsella** [comment]
maybe with a `Name` ?

**Comment by edouardpoitras** [comment]
Can now provide a custom pixel location for your popup as of 0.5.1: https://github.com/edouardpoitras/bevy_text_popup/blob/cea7eaf3082b18513953edf7b774b74a180c3eb6/examples/custom_locations.rs#L19

**Comment by edouardpoitras** [comment]
> maybe with a `Name` ?

Thanks, this is what I ended up doing. Not as ideal as a custom tag component, but that started to become a bit too complicated to implement with events.

A new `name` field has been added to the popup event type in 0.5.2. The Name component will be added to the root popup entity.
